2024-05-24 13:07:12,245 - ERROR - Error adding task: [Errno 2] No such file or directory: 'members.txt'
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 198, in add_members
    with open('members.txt', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'members.txt'
2024-05-24 13:25:26,504 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 207, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 13:28:12,683 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 208, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 13:41:20,823 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 208, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 13:42:14,009 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 208, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 13:42:58,772 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 208, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 15:24:51,680 - ERROR - Error in add_project function: cannot access local variable 'username' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 77, in add_project
    log_user_action(username, project_name)
                    ^^^^^^^^
UnboundLocalError: cannot access local variable 'username' where it is not associated with a value
2024-05-24 15:24:51,683 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 208, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 19:21:44,793 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 209, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 19:21:59,300 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 209, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
2024-05-24 19:22:18,774 - ERROR - Error adding task: cannot access local variable 'member_name' where it is not associated with a value
Traceback (most recent call last):
  File "c:\Users\admin\Documents\GitHub\Trellomize\main.py", line 209, in add_members
    log_system_event(f"member '{member_name}' Added successfully")
                                ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'member_name' where it is not associated with a value
